# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonPh' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "SnapKit", '~> 5.6.0'
  pod 'IQKeyboardManager' ,'6.5.6'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'FSPagerView'
  pod 'Alamofire', '= 5.0.0-rc.2'
  pod 'AlamofireObjectMapper'

  pod 'LookinServer', :configurations => ['Debug']
  
	
  # Pods for PokemonPh

end
